# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 850f9c689db7e296344c65771d08c91d91a24b32fb26d0296c61603980cf434aa7124e24723f8f9f35800f71ee3f190262f756f6ef1489c5ac7580a1b7874bdf

test:
  secret_key_base: 539b874dc18c059c63b88e278c7b8eb8c94ebc00da0004446198a62fafc1630bcd3cfcbb75c89f5db3b772501e7862deb4c76196a597b1914720693d36948c76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
